# -*- coding: utf-8 -*-
"""El mapa medido del video original 7678030150944001310 de @jcfdlw.

Una fila por toma: (n, ini, fin, tipo, loc, personajes, qué se ve).
Los tiempos NO son estimados: salen de la detección de cortes de ffmpeg
(`select=gt(scene,0.20)` sobre el .mp4 limpio, 1080x1920 con el cuadro real
recortado a 1080x1440) y de mirar el fotograma medio de cada toma.

Duración del archivo: 181.40 s. La última marca de la transcripción es 179.6 s,
así que el .txt corresponde a este archivo (y también al .full.mp4, que mide lo
mismo).

Regla de fusión: los tramos de menos de 0,5 s son destellos de transición, no
tomas; se suman a la toma anterior. Quedan 77 tomas, media 2,36 s.
"""

DURACION = 181.40

# n, ini, fin, tipo, loc, [personajes], qué se ve (castellano, para el mapa)
TOMAS = [
    (1, 0.00, 5.13, "PA", "azotea", ["mama"],
     "La mujer en la terraza-lavadero, de pie frente al tendedero lleno de ropa blanca, la ciudad detrás. Mira una prenda interior en las manos y busca entre las perchas."),
    (2, 5.13, 6.97, "PG", "colegio", ["duoduo"],
     "Salida del jardín de infantes: la nena con mochila rosa corre hacia cámara entre otros padres y chicos."),
    (3, 6.97, 7.50, "PM", "colegio", ["mama", "duoduo"],
     "La madre alza a la nena y la abraza; la nena le rodea el cuello."),
    (4, 7.50, 8.67, "PA", "salon", ["mama", "duoduo"],
     "Interior del salón en tonos rosados: la nena sentada en el puf con un globo, la madre sentada en el piso jugando con ella."),
    (5, 8.67, 11.77, "PM", "salon", ["mama", "duoduo"],
     "Perfil de las dos, la nena habla y la madre escucha; luz cálida y difusa."),
    (6, 11.77, 18.23, "PP", "salon", ["mama"],
     "Primer plano de la madre hablando, un dedo levantado; la nuca de la nena en el borde izquierdo del cuadro."),
    (7, 18.23, 19.93, "PP", "salon", ["duoduo"],
     "Primer plano de la nena con la mochila rosa puesta, la boca abierta."),
    (8, 19.93, 21.73, "PP", "salon", ["duoduo", "mama"],
     "La nena de perfil hablando, la cara de la madre entrando por el borde derecho."),
    (9, 21.73, 27.03, "PM", "salon", ["mama"],
     "La madre abrazando a la nena, que está de espaldas; la madre habla por encima de su hombro."),
    (10, 27.03, 29.97, "PP", "salon", ["duoduo"],
     "Primer plano de la nena, ojos entrecerrados, hablando."),
    (11, 29.97, 32.63, "PA", "colegio", ["mama", "duoduo"],
     "La madre agachada delante de la nena bajo el arco de colores del jardín, acomodándole la mochila."),
    (12, 32.63, 38.10, "PP", "colegio", ["duoduo"],
     "La nena en la vereda, mirándose las manos y contando con los dedos; motos borrosas detrás."),
    (13, 38.10, 39.20, "PP", "colegio", ["duoduo"],
     "La nena levanta la vista de los dedos y habla."),
    (14, 39.20, 45.67, "PP", "colegio", ["mama"],
     "Primer plano de la madre en la vereda, la cara quieta, los ojos muy abiertos."),
    (15, 45.67, 48.60, "PD", "auto", ["mama"],
     "Detalle: la mano de la madre sobre el volante y su torso, dentro del auto."),
    (16, 48.60, 50.73, "PM", "auto", ["mama"],
     "La madre al volante, de perfil, mirando de reojo hacia el asiento de atrás."),
    (17, 50.73, 52.50, "PP", "auto", ["mama"],
     "Primer plano de la madre al volante, de perfil, la calle desenfocada por la ventanilla."),
    (18, 52.50, 53.70, "PD", "auto", ["mama"],
     "Detalle de la mano apretando el volante y el cinturón cruzado."),
    (19, 53.70, 54.57, "PP", "auto", ["mama"],
     "La madre al volante en tres cuartos, mirando adelante."),
    (20, 54.57, 59.23, "PP", "auto", ["mama"],
     "Primer plano frontal a través del volante: la madre con los ojos enormes, la cara descompuesta."),
    (21, 59.23, 61.97, "PG", "pasillo", ["mama"],
     "Plano general del pasillo a oscuras: la madre de espaldas frente a la puerta del dormitorio, un cuchillo de cocina en la mano."),
    (22, 61.97, 64.37, "PA", "dormitorio", ["mama"],
     "La nuca de la madre a contraluz frente a las puertas corredizas del armario de madera oscura."),
    (23, 64.37, 66.77, "PA", "dormitorio", ["mama"],
     "Más cerca de la nuca y del armario: la mano subiendo hacia el tirador."),
    (24, 66.77, 69.50, "PA", "dormitorio", ["mama"],
     "La madre de pie en el dormitorio, de perfil, mirando el armario; la ventana con luz gris detrás."),
    (25, 69.50, 74.33, "PM", "dormitorio", ["mama"],
     "La madre se pasa la mano por el pelo y se ríe de sí misma, aliviada."),
    (26, 74.33, 75.67, "PG", "bano", ["mama", "duoduo"],
     "Plano general del baño: la nena en la bañera con espuma y un patito, la madre sentada en el borde lavándole el pelo."),
    (27, 75.67, 76.87, "PM", "bano", ["mama"],
     "La madre agachada junto a la bañera, estirando la mano hacia el patito."),
    (28, 76.87, 80.83, "PP", "bano", ["duoduo"],
     "Primer plano de la nena en el agua con el patito entre las manos; la mano de la madre en su pelo mojado."),
    (29, 80.83, 82.83, "PG", "bano", ["duoduo"],
     "El baño desde el otro lado: la nena chiquita en la bañera con los grifos en primer término."),
    (30, 82.83, 85.27, "PP", "bano", ["mama"],
     "Primer plano de la madre en pijama de seda, los ojos muy abiertos."),
    (31, 85.27, 88.53, "PM", "bano", ["duoduo"],
     "La nena en la bañera hablando, la boca abierta, el patito en la mano."),
    (32, 88.53, 89.40, "PP", "bano", ["mama"],
     "La madre baja la mirada, la boca entreabierta."),
    (33, 89.40, 90.47, "PM", "bano", ["duoduo"],
     "La nena mira hacia arriba, a la madre, mientras le enjuagan el pelo."),
    (34, 90.47, 93.97, "PM", "bano", ["mama"],
     "La madre inclinada sobre la bañera, sonriendo con la sonrisa forzada."),
    (35, 93.97, 97.67, "PP", "bano", ["mama"],
     "Primer plano muy cerrado de la madre, la mirada baja, la sonrisa ya apagada."),
    (36, 97.67, 99.50, "PP", "salon", ["mama"],
     "De noche: la cara de la madre iluminada de azul por la pantalla del celular."),
    (37, 99.50, 102.80, "PD", "salon", ["mama"],
     "Detalle del celular en la mano: un chat con una foto nocturna del skyline de Shanghái."),
    (38, 102.80, 105.03, "PD", "salon", ["mama"],
     "Detalle del celular: el muro de publicaciones con fotos y la ubicación repetida."),
    (39, 105.03, 108.83, "PM", "salon", ["mama"],
     "La madre en pijama sentada en el sofá a oscuras, el celular en las dos manos."),
    (40, 108.83, 109.37, "PG", "pasillo", [],
     "Plano general del pasillo a oscuras con la puerta entreabierta y una franja de luz."),
    (41, 109.37, 111.33, "PA", "pasillo", ["mama"],
     "La madre en pijama avanzando por el pasillo con el celular encendido en la mano."),
    (42, 111.33, 115.07, "PM", "pasillo", ["mama"],
     "La madre de perfil, la mano en el picaporte, el celular en la otra mano, la respiración cortada."),
    (43, 115.07, 116.67, "PM", "salon", ["duoduo"],
     "De día: la nena de rodillas en el sofá, hablándole a la madre, que está de espaldas."),
    (44, 116.67, 118.50, "PM", "salon", ["mama"],
     "La madre sonríe cansada, con ojeras; la nuca de la nena en primer término."),
    (45, 118.50, 119.63, "PM", "salon", ["duoduo"],
     "La nena pregunta, las manos apoyadas en las rodillas de la madre."),
    (46, 119.63, 121.23, "PM", "salon", ["mama", "duoduo"],
     "La madre levanta un dedo y cuenta algo, exagerando."),
    (47, 121.23, 122.47, "PM", "salon", ["mama"],
     "La madre se ríe con las dos manos en la boca."),
    (48, 122.47, 125.33, "PM", "auto", ["mama"],
     "La madre al volante, vista desde el asiento del acompañante, hablando hacia atrás."),
    (49, 125.33, 128.20, "PM", "auto", ["duoduo"],
     "La nena en la silla del auto con un conejo de peluche, hablando."),
    (50, 128.20, 129.80, "PM", "auto", ["mama"],
     "La madre al volante, la vista clavada adelante, preguntando."),
    (51, 129.80, 130.90, "PM", "auto", ["duoduo"],
     "La nena abraza el conejo y contesta."),
    (52, 130.90, 132.57, "PP", "auto", ["mama"],
     "Primer plano muy cerrado de la madre en el auto, la mandíbula tensa."),
    (53, 132.57, 134.30, "PM", "auto", ["mama"],
     "La madre al volante con el brazo estirado, hablando hacia el espejo."),
    (54, 134.30, 136.27, "PM", "auto", ["duoduo"],
     "La nena mirando hacia abajo, jugando con las orejas del conejo."),
    (55, 136.27, 137.80, "PM", "auto", ["duoduo"],
     "La nena levanta la cara hacia el espejo y dice algo."),
    (56, 137.80, 138.90, "PM", "auto", ["mama"],
     "La madre gira apenas la cabeza, de perfil."),
    (57, 138.90, 141.10, "PM", "auto", ["duoduo"],
     "La nena se encoge de hombros, abrazada al conejo."),
    (58, 141.10, 143.20, "PD", "auto", ["mama"],
     "Detalle del espejo retrovisor con los ojos de la madre reflejados; la calle desenfocada."),
    (59, 143.20, 148.80, "PM", "auto", ["mama"],
     "La madre al volante, decidida, contando dos cosas con la voz."),
    (60, 148.80, 150.13, "PM", "tienda", ["mama"],
     "La madre inclinada sobre el mostrador de una tienda de electrónica, pidiendo algo."),
    (61, 150.13, 152.07, "PM", "tienda", ["mama"],
     "La madre apoyada en la vitrina, insistiendo, con los estantes de accesorios detrás."),
    (62, 152.07, 152.57, "PM", "tienda", ["vendedora"],
     "La vendedora de uniforme negro detrás del mostrador, buscando algo en la vitrina."),
    (63, 152.57, 153.33, "PM", "tienda", ["vendedora"],
     "La vendedora levanta una cámara diminuta entre los dedos y la muestra."),
    (64, 153.33, 154.47, "PA", "tienda", ["vendedora"],
     "La vendedora estira el brazo con la cámara en la palma, hablando."),
    (65, 154.47, 157.70, "PD", "tienda", ["mama"],
     "Detalle de la mano de la madre sosteniendo la minicámara negra a contraluz."),
    (66, 157.70, 158.90, "PM", "tienda", ["mama"],
     "La madre sobre el mostrador con la cámara en una mano y el celular en la otra."),
    (67, 158.90, 161.63, "PP", "pasillo", ["mama"],
     "Primer plano de la madre en el pasillo de casa, hablándose a sí misma para darse coraje antes de entrar al dormitorio."),
    (68, 161.63, 162.50, "PD", "dormitorio", ["mama"],
     "Detalle del cuello y el pecho de la madre con el celular naranja en la mano."),
    (69, 162.50, 163.67, "PD", "dormitorio", ["mama"],
     "Detalle de la pantalla del celular: la vista de la cámara oculta, con el armario entero en cuadro."),
    (70, 163.67, 168.63, "PM", "cocina", ["mama"],
     "La madre agachada frente a la heladera abierta, contando los envases de leche."),
    (71, 168.63, 171.57, "PM", "cocina", ["mama"],
     "La madre de perfil contando los huevos en la bandeja de la puerta de la heladera."),
    (72, 171.57, 175.07, "PP", "cocina", ["mama"],
     "Primer plano de la madre frente a la heladera, la cuenta que no da, la boca abierta."),
    (73, 175.07, 176.27, "PM", "cocina", ["mama"],
     "La madre se endereza y mira hacia el escurridor, la heladera abierta detrás."),
    (74, 176.27, 177.70, "PD", "cocina", ["mama"],
     "Detalle del escurridor junto a la ventana: los cuencos boca abajo y uno solo boca arriba."),
    (75, 177.70, 178.67, "PM", "cocina", ["mama"],
     "La madre de pie en la cocina con un cuenco en la mano, una gota de sudor en la sien."),
    (76, 178.67, 179.57, "PD", "cocina", ["mama"],
     "Detalle extremo: la yema del dedo recorriendo el interior del cuenco."),
    (77, 179.57, 181.40, "PGE", "cosmos", [],
     "Placa final: una nebulosa púrpura y azul con estrellas, sobre la que va el llamado a seguir mirando."),
]

assert len(TOMAS) == 77
assert abs(TOMAS[-1][2] - DURACION) < 0.01
